const timeList = ["10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00"];

const data = [{
        id: "m10",
        title: "",
        participants: [],
        day: "Monday",
        time: "10:00",
        availability: true,
    },
    {
        id: "t10",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "10:00",
        availability: true,
    },
    {
        id: "w10",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "10:00",
        availability: true,
    },
    {
        id: "th10",
        title: "",
        participants: [],
        day: "Thursday",
        time: "10:00",
        availability: true,
    },
    {
        id: "f10",
        title: "",
        participants: [],
        day: "Friday",
        time: "10:00",
        availability: true,
    },

    {   id: "m11",
        title: "Daily Standup",
        participants: "Dr. Dre",
        day: "Monday",
        time: "11:00",
        availability: false,
    },
    {
        id: "t11",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "11:00",
        availability: true,
    },
    {
        id: "w11",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "11:00",
        availability: true,
    },
    {
        id: "th11",
        title: "",
        participants: [],
        day: "Thursday",
        time: "11:00",
        availability: true,
    },
    {
        id: "f11",
        title: "",
        participants: [],
        day: "Friday",
        time: "11:00",
        availability: true,
    },
    {   id: "m12",
        title: "",
        participants: [],
        day: "Monday",
        time: "12:00",
        availability: true,
    },
    {
        id: "t12",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "12:00",
        availability: true,
    },
    {
        id: "w12",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "12:00",
        availability: true,
    },
    {
        id: "th12",
        title: "",
        participants: [],
        day: "Thursday",
        time: "12:00",
        availability: true,
    },
    {
        id: "f12",
        title: "",
        participants: [],
        day: "Friday",
        time: "12:00",
        availability: true,
    },
    {   id: "m13",
        title: "",
        participants: [],
        day: "Monday",
        time: "13:00",
        availability: true,
    },
    {
        id: "t13",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "13:00",
        availability: true,
    },
    {
        id: "w13",
        title: "Planning Session",
        participants: "Anna Lavrinchuk",
        day: "Wednesday",
        time: "13:00",
        availability: false,
    },
    {
        id: "th13",
        title: "",
        participants: [],
        day: "Thursday",
        time: "13:00",
        availability: true,
    },
    {
        id: "f13",
        title: "",
        participants: [],
        day: "Friday",
        time: "13:00",
        availability: true,
    },
    {   id: "m14",
        title: "Shopping Designed",
        participants: "Dr. Dre",
        day: "Monday",
        time: "14:00",
        availability: false,
    },
    {
        id: "t14",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "14:00",
        availability: true,
    },
    {
        id: "w14",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "14:00",
        availability: true,
    },
    {
        id: "th14",
        title: "",
        participants: [],
        day: "Thursday",
        time: "14:00",
        availability: true,
    },
    {
        id: "f14",
        title: "",
        participants: [],
        day: "Friday",
        time: "14:00",
        availability: true,
    },
    {   id: "m15",
        title: "",
        participants: [],
        day: "Monday",
        time: "15:00",
        availability: true,
    },
    {
        id: "t15",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "15:00",
        availability: true,
    },
    {
        id: "w15",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "15:00",
        availability: true,
    },
    {
        id: "th15",
        title: "",
        participants: [],
        day: "Thursday",
        time: "15:00",
        availability: true,
    },
    {
        id: "f15",
        title: "",
        participants: [],
        day: "Friday",
        time: "15:00",
        availability: true,
    },
    {   id: "m16",
        title: "",
        participants: [],
        day: "Monday",
        time: "16:00",
        availability: true,
    },
    {
        id: "t16",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "16:00",
        availability: true,
    },
    {
        id: "w16",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "16:00",
        availability: true,
    },
    {
        id: "th16",
        title: "",
        participants: [],
        day: "Thursday",
        time: "16:00",
        availability: true,
    },
    {
        id: "f16",
        title: "",
        participants: [],
        day: "Friday",
        time: "16:00",
        availability: true,
    },
    {   id: "m17",
        title: "",
        participants: [],
        day: "Monday",
        time: "17:00",
        availability: true,
    },
    {
        id: "t17",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "17:00",
        availability: true,
    },
    {
        id: "w17",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "17:00",
        availability: true,
    },
    {
        id: "th17",
        title: "",
        participants: [],
        day: "Thursday",
        time: "17:00",
        availability: true,
    },
    {
        id: "f17",
        title: "Retrospective",
        participants: "Mike Dobkin",
        day: "Friday",
        time: "17:00",
        availability: false,
    },
    {   id: "m18",
        title: "",
        participants: [],
        day: "Monday",
        time: "18:00",
        availability: true,
    },
    {
        id: "t18",
        title: "",
        participants: [],
        day: "Tuesday",
        time: "18:00",
        availability: true,
    },
    {
        id: "w18",
        title: "",
        participants: [],
        day: "Wednesday",
        time: "18:00",
        availability: true,
    },
    {
        id: "th18",
        title: "",
        participants: [],
        day: "Thursday",
        time: "18:00",
        availability: true,
    },
    {
        id: "f18",
        title: "",
        participants: [],
        day: "Friday",
        time: "18:00",
        availability: true,
    },
];

let lsData = [];